### ISSUE TITLE
Improved JSON Error handling

### ISSUE THREAD

**Issue by machajdik** [placemarkt/address-formatter-java#3]
In method `AddressFormatter.format(String, String)` when a `JsonProcessingException` occurs, a new `IOException` is generated. Please also add the original Exception to the new Exception:

```
    try {
       components = yamlReader.readValue(json, type);
    } catch (JsonProcessingException e) {
      throw(new IOException("Json processing exception", e));
    }
```

many thanks!

**Comment by rkoeze** [comment]
@machajdik Thank you! I'll take a look this week.

**Comment by rkoeze** [comment]
@machajdik Fix here: https://github.com/placemarkt/address-formatter-java/pull/4

I'll ping you again and close this issue when it gets deployed.

**Comment by rkoeze** [comment]
Just finished deploying. It may take a bit more time to sync with Maven Central. I will close this issue when it does. Thanks!
