### ISSUE TITLE
Possibility fo update yaml config files from OpenCageData/address-formatting

### ISSUE THREAD

**Issue by machajdik** [placemarkt/address-formatter-java#6]
Hi,
some country configuration is outdated, but already fixed in `OpenCageData/address-formatting`. Is there a way for a user of this project to upgrade the yaml config files from `OpenCageData/address-formatting`? Or do you have to do it and release a new version?

Cheers,
Manuel

**Comment by rkoeze** [comment]
Hey Manuel! No, that's on me. I'll have to release a new version. I will have that done in the next week or so. Does that sound good to you? Thanks for the reminder.

**Comment by machajdik** [comment]
sure, absolutely no rush. thanks!

**Comment by machajdik** [comment]
hi, just wanted to check back on this.

**Comment by rkoeze** [comment]
Hi @machajdik, sorry. See my comment [here](https://github.com/placemarkt/address-formatter-java/issues/8#issuecomment-2351084285). Thanks for your patience!

**Comment by rkoeze** [comment]
@machajdik package updated. Current latest is 0.0.11.

**Comment by machajdik** [comment]
Great, thanks! And congratulations :)

**Comment by rkoeze** [comment]
Thank you!
