### ISSUE TITLE
Update to current upstream

### ISSUE THREAD

**Issue by bbiallowons** [placemarkt/address-formatter-java#8]
Hey! Many thanks for your efforts maintaining this project, really appreciated!

Is there a chance that this project will update to the current upstream?

BR

**Comment by bbiallowons** [comment]
Hey! Any chance you could give an update on this topic?

**Comment by rkoeze** [comment]
Hi @bbiallowons! Sorry for the late reply. I became a father recently and have been adjusting to a new set of priorities! I have time now and will get right on it. Will link the PR here when it's ready.

**Comment by rkoeze** [comment]
PR is [here](https://github.com/placemarkt/address-formatter-java/pull/9). Currently a WIP as some tests are failing.

**Comment by rkoeze** [comment]
PR [merged](https://github.com/placemarkt/address-formatter-java/pull/9). Will release the package in the next couple of days.

**Comment by rkoeze** [comment]
The most recent release has been updated to the current upstream, thanks!

**Comment by bbiallowons** [comment]
Sry for the late reply, thank you!
